# Generated by Django 6.0.6 on 2026-06-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('input_format', models.CharField(choices=[('FASTQ', 'FASTQ'), ('FASTA', 'FASTA')], default='FASTQ', max_length=10)),
                ('total_reads', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Importé'), ('PROCESSING', 'En traitement'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FastaConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mean_quality', models.IntegerField()),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('reads_kept', models.IntegerField(default=0)),
                ('reads_discarded', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='fasta/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='back.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KmerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField()),
                ('source', models.CharField(choices=[('RAW', 'Reads bruts'), ('FILTERED', 'Reads filtrés')], default='RAW', max_length=10)),
                ('total_kmers', models.BigIntegerField(default=0)),
                ('distinct_kmers', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kmer_analyses', to='back.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KmerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='back.kmeranalysis')),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='KmerSpectrumBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplicity', models.IntegerField()),
                ('distinct_count', models.BigIntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum', to='back.kmeranalysis')),
            ],
            options={
                'ordering': ['multiplicity'],
            },
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_quality', models.FloatField()),
                ('min_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('mean_length', models.FloatField()),
                ('gc_content', models.FloatField()),
                ('per_position_quality', models.JSONField(default=list)),
                ('length_distribution', models.JSONField(default=dict)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='back.dataset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kmeranalysis',
            constraint=models.UniqueConstraint(fields=('dataset', 'k', 'source'), name='unique_kmer_run'),
        ),
        migrations.AddIndex(
            model_name='kmercount',
            index=models.Index(fields=['analysis', '-count'], name='back_kmerco_analysi_6f272f_idx'),
        ),
        migrations.AddConstraint(
            model_name='kmerspectrumbin',
            constraint=models.UniqueConstraint(fields=('analysis', 'multiplicity'), name='unique_spectrum_bin'),
        ),
    ]
