# Generated by Django 6.0.6 on 2026-06-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_a_label', models.CharField(max_length=255)),
                ('read_a_sequence', models.TextField()),
                ('read_a_index', models.IntegerField(blank=True, null=True)),
                ('read_b_label', models.CharField(max_length=255)),
                ('read_b_sequence', models.TextField()),
                ('read_b_index', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('read_a_start', models.IntegerField(blank=True, null=True)),
                ('read_a_end', models.IntegerField(blank=True, null=True)),
                ('read_b_start', models.IntegerField(blank=True, null=True)),
                ('read_b_end', models.IntegerField(blank=True, null=True)),
                ('aligned_a', models.TextField()),
                ('match_line', models.TextField()),
                ('aligned_b', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignments_as_a', to='back.dataset')),
                ('dataset_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignments_as_b', to='back.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
