# Generated by Django 6.0.6 on 2026-06-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alignmentrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('RAW', 'Reads bruts'), ('FILTERED', 'Reads filtrés')], default='RAW', max_length=10)),
                ('k', models.IntegerField()),
                ('solidity_threshold', models.IntegerField()),
                ('bloom_bits', models.BigIntegerField()),
                ('num_hashes', models.IntegerField()),
                ('distinct_kmers', models.BigIntegerField(default=0)),
                ('solid_kmers', models.BigIntegerField(default=0)),
                ('bloom_fp_rate', models.FloatField(default=0.0)),
                ('bloom_bytes', models.BigIntegerField(default=0)),
                ('dict_bytes_estimate', models.BigIntegerField(default=0)),
                ('num_contigs', models.IntegerField(default=0)),
                ('max_contig_length', models.IntegerField(default=0)),
                ('total_contig_length', models.BigIntegerField(default=0)),
                ('reference_sequence', models.TextField(blank=True)),
                ('best_identity', models.FloatField(blank=True, null=True)),
                ('contigs_file', models.FileField(blank=True, null=True, upload_to='assemblies/')),
                ('status', models.CharField(choices=[('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='DONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='back.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('identity_to_reference', models.FloatField(blank=True, null=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contigs', to='back.assemblyrun')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
